version: 0.2

phases: 
    install:
        runtime-versions:
            python: Python 3.8
        commands: 
            - echo Entered the install phase ...
            - sudo apt install python3 python3-pip -y
         
    build:
        commands: 
            - echo Entered the build phase ...
            - mvn clean install
artifacts:
    files:
        - */<APP_NAME>-0.0.1-SNAPSHOT.jar
