version: 0.2

phases: 
    install:
        runtime-versions:
            python: Python 3.8
        commands: 
            - echo Entered the install phase ...
            - sudo apt install python3 python3-pip -y
            - sudo apt install python3-venv -y
            - python3 -m venv game-venv
         
    build:
        commands: 
            - echo Entered the build phase ...
            - sudo cp etc/systemd/system/flask.service /etc/systemd/system
            - sudo systemctl daemon-reload
            - sudo systemctl enable flask.service
            - source game-venv/bin/activate
            - sudo systemctl start flask.service
            - pip3 install -r ./requirements.txt
artifacts:
    files:
        - */<APP_NAME>-0.0.1-SNAPSHOT.jar
