version: '3.7'
services:
  Game-Review-Library:
    image: Game-Review-Library
    build: ./Game-Review-Library
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  mysql:
    image: mysql:latest
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: mysql
      target: /var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf

  environment:
    MYSQL_DATABASE: ${MYSQL_DATABASE}
volumes:
  mysql: